import{A as w,S as v,i as a}from"./assets/vendor-b41355b7.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const S=w.create({baseURL:"https://pixabay.com/api/",params:{key:"44419663-0e2c09df92781957132f7cc0f",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});async function h(o,e){try{const i=await S.get("",{params:{q:o,page:e}});return console.log(i),i.data}catch(i){console.log(i)}}const x=document.querySelector(".image-list");function y(o){const e=o.map(s=>`
    <li class="images-item">
    <a class="large-img-link" href="${s.largeImageURL}">
    <img class="small-img-link" src="${s.webformatURL}" alt="${s.tags}"></img>
    <div class="image-box">
    <p class="img-list-item-text">Likes: ${s.likes}</p>
    <p class="img-list-item-text">Views: ${s.views}</p>
    <p class="img-list-item-text">Comments: ${s.comments}</p>
    <p class="img-list-item-text">Downloads: ${s.downloads}</p>
    </div>
        </a>
    </li>`).join("");return x.innerHTML=e,new v(".image-list a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh(),e}const q=document.querySelector(".form-js"),M=document.querySelector(".input-js"),f=document.querySelector(".image-list"),L=document.querySelector(".loader"),p=document.querySelector(".btn-load-more");let c="",n=1,d=1;const P=15;q.addEventListener("submit",async o=>{if(o.preventDefault(),c=M.value.trim(),n=1,f.innerHTML="",b(),g(),c===""){a.warning({title:"Warning!",message:"Query must be field!",position:"topRight",backgroundColor:"#ef4040",layout:2}),l();return}try{const e=await h(c,n);if(console.log(e),d=Math.ceil(e.totalHits/P),d===0){a.error({title:"Empty result",message:"No images found!"}),l(),m();return}y(e.hits)}catch{a.error({message:"Error!"})}l(),m(),o.target.reset()});p.addEventListener("click",async()=>{n++,g(),b();try{const o=await h(c,n);f.insertAdjacentHTML("beforeend",y(o.hits)),E()}catch{console.log("error")}l(),m()});function m(){n>=d?(g(),d!==0&&a.info({message:"We're sorry, but you've reached the end of search results."})):$()}function $(){p.classList.remove("hidden")}function g(){p.classList.add("hidden")}function b(){L.classList.remove("hidden")}function l(){L.classList.add("hidden")}function E(){const o=f.querySelector(".images-item");if(o){const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
