import{A as S,S as b,i as c}from"./assets/vendor-b41355b7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();document.querySelector(".form-js");document.querySelector(".input-js");document.querySelector(".image-list");const q=S.create({baseURL:"https://pixabay.com/api/",params:{key:"44419663-0e2c09df92781957132f7cc0f",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});async function u(o,t){try{const r=await q.get("",{params:{q:o,page:t}});return console.log(r),r.data}catch(r){console.log(r)}}document.querySelector(".form-js");document.querySelector(".input-js");const w=document.querySelector(".image-list");function d(o){const t=o.map(i=>`
    <li class="images-item">
    <a class="large-img-link" href="${i.largeImageURL}">
    <img class="small-img-link" src="${i.webformatURL}" alt="${i.tags}"></img>
    <div class="image-box">
    <p class="img-list-item-text">Likes: ${i.likes}</p>
    <p class="img-list-item-text">Views: ${i.views}</p>
    <p class="img-list-item-text">Comments: ${i.comments}</p>
    <p class="img-list-item-text">Downloads: ${i.downloads}</p>
    </div>
        </a>
    </li>`).join("");w.innerHTML=t,new b(".image-list a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const v=document.querySelector(".form-js"),g=document.querySelector(".input-js"),m=document.querySelector(".image-list"),h=document.querySelector(".loader"),x=document.querySelector(".btn-js"),f=document.querySelector(".btn-load-more");v.addEventListener("submit",async o=>{o.preventDefault();const t=g.value.trim();t===""&&(m.innerHTML=" "),M();try{const r=await u(t);r.hits.length!==0?d(r.hits):c.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fafafa",color:"#ef4040",position:"topRight"})}catch{c.error({message:"An error occurred while fetching images. Please try again later."})}$(),o.target.reset()});let l="",n=1,y=1;const P=15;x.addEventListener("click",async()=>{l=g.value.trim(),n=1,p();const o=await u(l,n);console.log(o),y=Math.ceil(o.totalHits/P);const t=d(o.hits);m.innerHTML=t,L()});f.addEventListener("click",async()=>{n++,p();const o=await u(l,n),t=d(o.hits);m.insertAdjacentElement("beforeend",t),L()});function L(){n>=y?(p(),c.info({title:"The End!",message:"The end of collection"})):j()}function j(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}function M(){h.classList.remove("hidden")}function $(){h.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
